from typing import Literal, cast

SelectAction = Literal['ASSERTSL_DEASSERTSL', 'ASSERTSL_NOTHING', 'DEASSERTSL_ASSERTSL', 'DEASSERTSL_NOTHING', 'FLIPAB_NOTHING', 'INVA_INVB', 'INVA_NOTHING', 'INVB_INVA', 'INVB_NOTHING', 'NEGATESL_NOTHING', 'NOTHING_ASSERTSL', 'NOTHING_DEASSERTSL', 'NOTHING_FLIPAB', 'NOTHING_INVA', 'NOTHING_INVB', 'NOTHING_NEGATESL']

SELECT_ACTION_VALUES: set[SelectAction] = { 'ASSERTSL_DEASSERTSL', 'ASSERTSL_NOTHING', 'DEASSERTSL_ASSERTSL', 'DEASSERTSL_NOTHING', 'FLIPAB_NOTHING', 'INVA_INVB', 'INVA_NOTHING', 'INVB_INVA', 'INVB_NOTHING', 'NEGATESL_NOTHING', 'NOTHING_ASSERTSL', 'NOTHING_DEASSERTSL', 'NOTHING_FLIPAB', 'NOTHING_INVA', 'NOTHING_INVB', 'NOTHING_NEGATESL',  }

def check_select_action(value: str) -> SelectAction:
    if value in SELECT_ACTION_VALUES:
        return cast(SelectAction, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {SELECT_ACTION_VALUES!r}")
